version: 2
jobs:
  build-job:
    docker:
      - image: cypress/base:8
      - image: mongo:3.4.4
    working_directory: ~/sdjs-speaker-pipeline
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: build files
          command: npm run build
      - run: npm run test
  deploy-job:
    working_directory: ~/sdjs-speaker-pipeline
    docker:
      - image: circleci/node:8.11.0
    steps:
      - checkout
      - run:
          name: Run Heroku setup
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "c6:4f:a8:c5:a8:4b:5a:cc:52:ee:a3:06:c5:9e:1a:da"
      - deploy:
          name: Deploy Master to Heroku
          command: git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
